export const DATA = [
    {
        id: 1,
        departureTime: "06:35",
        arrivalTime: "12:48",
        seats: 7,
        busProvider: "NueGo",
        busType: "Electric A/C Seater(2+2)",
        ratings: "4",
        startingFrom: "290",
        journeyDuration: "7h 30m",
    },
    {
        id: 2,
        departureTime: "07:35",
        arrivalTime: "13:48",
        seats: 8,
        busProvider: "TransitX",
        busType: "Luxury Sleeper(1+1)",
        ratings: "4.5",
        startingFrom: "320",
        journeyDuration: "8h 15m",
    },
    {
        id: 3,
        departureTime: "08:35",
        arrivalTime: "14:48",
        seats: 10,
        busProvider: "SpeedyBus",
        busType: "Semi-Sleeper(2+1)",
        ratings: "4.2",
        startingFrom: "350",
        journeyDuration: "6h 45m",
    },
    {
        id: 4,
        departureTime: "09:35",
        arrivalTime: "15:48",
        seats: 6,
        busProvider: "ComfortTrans",
        busType: "Standard A/C Seater(2+2)",
        ratings: "3.8",
        startingFrom: "270",
        journeyDuration: "7h 55m",
    },
    {
        id: 5,
        departureTime: "10:35",
        arrivalTime: "16:48",
        seats: 9,
        busProvider: "SwiftTrans",
        busType: "Sleeper(2+1)",
        ratings: "4.7",
        startingFrom: "380",
        journeyDuration: "8h 30m",
    },
    {
        id: 6,
        departureTime: "11:35",
        arrivalTime: "17:48",
        seats: 5,
        busProvider: "FlyRide",
        busType: "Executive A/C Seater(2+2)",
        ratings: "4.3",
        startingFrom: "300",
        journeyDuration: "7h 20m",
    },
    {
        id: 7,
        departureTime: "12:35",
        arrivalTime: "18:48",
        seats: 7,
        busProvider: "ExpressLux",
        busType: "Volvo Multi-Axle Sleeper(2+1)",
        ratings: "4.6",
        startingFrom: "400",
        journeyDuration: "8h 45m",
    },
    {
        id: 8,
        departureTime: "13:35",
        arrivalTime: "19:48",
        seats: 8,
        busProvider: "SuperTrans",
        busType: "Deluxe Non A/C Seater(2+2)",
        ratings: "4.1",
        startingFrom: "340",
        journeyDuration: "7h 10m",
    },
    {
        id: 9,
        departureTime: "14:35",
        arrivalTime: "20:48",
        seats: 6,
        busProvider: "CityLink",
        busType: "Semi-Sleeper(2+1)",
        ratings: "4.4",
        startingFrom: "370",
        journeyDuration: "7h 40m",
    },
    {
        id: 10,
        departureTime: "15:35",
        arrivalTime: "21:48",
        seats: 9,
        busProvider: "RoyalRide",
        busType: "Luxury A/C Sleeper(1+1)",
        ratings: "4.8",
        startingFrom: "420",
        journeyDuration: "8h 15m",
    },
    {
        id: 11,
        departureTime: "15:35",
        arrivalTime: "21:48",
        seats: 9,
        busProvider: "RoyalRide",
        busType: "Luxury A/C Sleeper(1+1)",
        ratings: "4.8",
        startingFrom: "420",
        journeyDuration: "8h 15m",
    },
    {
        id: 12,
        departureTime: "15:35",
        arrivalTime: "21:48",
        seats: 9,
        busProvider: "RoyalRide",
        busType: "Luxury A/C Sleeper(1+1)",
        ratings: "4.8",
        startingFrom: "420",
        journeyDuration: "8h 15m",
    },
    {
        id: 13,
        departureTime: "15:35",
        arrivalTime: "21:48",
        seats: 9,
        busProvider: "RoyalRide",
        busType: "Luxury A/C Sleeper(1+1)",
        ratings: "4.8",
        startingFrom: "420",
        journeyDuration: "8h 15m",
    },
    {
        id: 14,   //Primary key for a bus
        departureTime: "19:35",
        arrivalTime: "11:48",
        seats: 9,
        busProvider: "RoyalRide",
        busType: "Luxury A/C Sleeper(1+1)",
        ratings: "4.8",
        startingFrom: "420",
        journeyDuration: "8h 15m",
    },
];
